-- FINAL SOLUTION: Create Demo Pediatrician User "Dr. Smith"
-- This script works around the foreign key constraint by checking existing users
-- Run fix_profiles_role_constraint.sql FIRST, then run this

-- Step 1: Check what user IDs exist in your profiles table
SELECT id, username, role 
FROM profiles 
ORDER BY created_at 
LIMIT 10;

-- Step 2: After seeing the IDs above, use ONE of these approaches:

-- APPROACH A: If you see existing users (Daddy Cool, Timmy Turner, etc.)
-- Copy one of their IDs and use it to create a pattern
-- Then run this (replace EXISTING_USER_ID with an actual ID from Step 1):
/*
DO $$
DECLARE
  existing_id UUID;
  profile_exists BOOLEAN;
BEGIN
  -- Get an existing user ID
  SELECT id INTO existing_id FROM profiles WHERE username IN ('Daddy Cool', 'Timmy Turner') LIMIT 1;
  
  IF existing_id IS NULL THEN
    RAISE EXCEPTION 'No existing users found. Please create a user via Supabase Auth first.';
  END IF;
  
  -- Check if Dr. Smith already exists
  SELECT EXISTS(SELECT 1 FROM profiles WHERE username = 'Dr. Smith') INTO profile_exists;
  
  IF NOT profile_exists THEN
    -- Create profile - the ID will be auto-generated by Supabase if there's a default
    -- But we need to ensure it references auth.users
    -- Try inserting without specifying ID first
    INSERT INTO profiles (username, role, family_id, wallet_address)
    VALUES ('Dr. Smith', 'pediatrician', gen_random_uuid(), NULL);
    
    RAISE NOTICE 'Created profile for Dr. Smith';
  ELSE
    UPDATE profiles SET role = 'pediatrician' WHERE username = 'Dr. Smith';
    RAISE NOTICE 'Updated existing profile';
  END IF;
END $$;
*/

-- APPROACH B: Create via Supabase Dashboard (RECOMMENDED)
-- 1. Go to Supabase Dashboard > Authentication > Users
-- 2. Click "Add User" 
-- 3. Email: dr.smith@kiddyguard.demo
-- 4. Password: (set any password, e.g., "demo123")
-- 5. Copy the User ID that gets created
-- 6. Run this SQL with that User ID:

-- INSERT INTO profiles (id, username, role, family_id, wallet_address)
-- VALUES (
--   'PASTE_USER_ID_HERE',  -- The UUID from Authentication > Users
--   'Dr. Smith',
--   'pediatrician',
--   gen_random_uuid(),
--   NULL
-- );

-- APPROACH C: If profiles.id has a default value or trigger
-- Try inserting without specifying the ID:
INSERT INTO profiles (username, role, family_id, wallet_address)
SELECT 'Dr. Smith', 'pediatrician', gen_random_uuid(), NULL
WHERE NOT EXISTS (SELECT 1 FROM profiles WHERE username = 'Dr. Smith');

-- If that fails, update existing user:
UPDATE profiles
SET role = 'pediatrician'
WHERE username = 'Dr. Smith' AND role != 'pediatrician';

-- Verify
SELECT id, username, role, family_id, created_at
FROM profiles
WHERE username = 'Dr. Smith';

